"""GST-compliant invoice PDF generator with mock IRN and QR code."""

import hashlib
import io
import uuid
from datetime import datetime

import qrcode
from fpdf import FPDF
from models.invoice import Invoice


def generate_invoice_number() -> str:
    """Generate a sequential-looking invoice number."""
    now = datetime.now()
    seq = uuid.uuid4().hex[:4].upper()
    return f"INV-{now.year}-{now.month:02d}{seq}"


def generate_mock_irn(invoice: Invoice) -> str:
    """Generate a mock 64-char IRN hash (simulating GSP/IRP response)."""
    seed = f"{invoice.seller_gstin}{invoice.invoice_number}{invoice.date}"
    return hashlib.sha256(seed.encode()).hexdigest()


def generate_qr_bytes(irn: str) -> bytes:
    """Generate QR code PNG bytes for the IRN."""
    qr = qrcode.make(irn)
    buf = io.BytesIO()
    qr.save(buf, format="PNG")
    return buf.getvalue()


def generate_invoice_pdf(invoice: Invoice) -> bytes:
    """Generate a GST-compliant invoice PDF and return bytes."""
    # Ensure invoice number exists
    if not invoice.invoice_number:
        invoice.invoice_number = generate_invoice_number()

    irn = generate_mock_irn(invoice)

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- Header ---
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, "TAX INVOICE", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # --- Invoice meta ---
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(95, 6, f"Invoice #: {invoice.invoice_number}")
    pdf.cell(95, 6, f"Date: {invoice.date}", align="R", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # --- Seller / Buyer ---
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(95, 6, "Seller", new_x="END")
    pdf.cell(95, 6, "Buyer", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 9)
    pdf.cell(95, 5, invoice.seller_name or "Demo Seller", new_x="END")
    pdf.cell(95, 5, invoice.buyer_name or "-", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(95, 5, f"GSTIN: {invoice.seller_gstin or 'N/A'}", new_x="END")
    pdf.cell(95, 5, f"GSTIN: {invoice.buyer_gstin or 'N/A'}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # --- Line items table ---
    pdf.set_font("Helvetica", "B", 9)
    col_w = [10, 70, 25, 20, 25, 40]
    headers = ["#", "Description", "Qty", "Unit", "Rate", "Amount"]
    for i, h in enumerate(headers):
        pdf.cell(col_w[i], 8, h, border=1, align="C")
    pdf.ln()

    pdf.set_font("Helvetica", "", 9)
    for idx, item in enumerate(invoice.items, 1):
        pdf.cell(col_w[0], 7, str(idx), border=1, align="C")
        pdf.cell(col_w[1], 7, item.description[:35], border=1)
        pdf.cell(col_w[2], 7, f"{item.quantity:g}", border=1, align="R")
        pdf.cell(col_w[3], 7, item.unit, border=1, align="C")
        pdf.cell(col_w[4], 7, f"{item.rate:,.0f}", border=1, align="R")
        pdf.cell(col_w[5], 7, f"{item.amount:,.2f}", border=1, align="R")
        pdf.ln()

    pdf.ln(4)

    # --- Totals ---
    x_label = 130
    pdf.set_font("Helvetica", "", 10)
    pdf.set_x(x_label)
    pdf.cell(30, 6, "Subtotal:", align="R")
    pdf.cell(30, 6, f"Rs. {invoice.subtotal:,.2f}", align="R", new_x="LMARGIN", new_y="NEXT")

    half_rate = invoice.gst_rate / 2
    if invoice.is_interstate:
        pdf.set_x(x_label)
        pdf.cell(30, 6, f"IGST ({invoice.gst_rate}%):", align="R")
        pdf.cell(30, 6, f"Rs. {invoice.igst:,.2f}", align="R", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_x(x_label)
        pdf.cell(30, 6, f"CGST ({half_rate}%):", align="R")
        pdf.cell(30, 6, f"Rs. {invoice.cgst:,.2f}", align="R", new_x="LMARGIN", new_y="NEXT")
        pdf.set_x(x_label)
        pdf.cell(30, 6, f"SGST ({half_rate}%):", align="R")
        pdf.cell(30, 6, f"Rs. {invoice.sgst:,.2f}", align="R", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_x(x_label)
    pdf.cell(30, 8, "Total:", align="R")
    pdf.cell(30, 8, f"Rs. {invoice.total:,.2f}", align="R", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # --- IRN ---
    pdf.set_font("Helvetica", "", 7)
    pdf.cell(0, 4, f"IRN: {irn}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # --- QR Code ---
    qr_bytes = generate_qr_bytes(irn)
    qr_stream = io.BytesIO(qr_bytes)
    pdf.image(qr_stream, x=10, w=30)

    # --- Footer ---
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 7)
    pdf.cell(0, 4, "Generated by BillKaro | Powered by Sarvam", align="C")

    return bytes(pdf.output())
